In [2]:
import numpy as np

a = np.random.randint(0,10,size=[10,10])
print(a)

[[6 2 3 4 5 3 8 6 3 6]
 [6 6 1 9 2 0 7 0 1 3]
 [3 9 7 1 7 5 2 8 4 4]
 [8 4 9 2 6 5 1 8 9 8]
 [7 6 0 4 9 9 8 1 9 7]
 [9 0 9 1 0 0 9 0 0 6]
 [6 8 7 0 6 1 9 5 5 1]
 [7 0 6 2 7 8 9 8 0 6]
 [7 4 6 2 6 0 6 9 1 5]
 [6 7 7 5 4 1 8 2 6 6]]


In [6]:
i=0
print(a[i:i+3, i:i+3])

[[6 2 3]
 [6 6 1]
 [3 9 7]]


In [7]:
print(np.mean(a[i:i+3, i:i+3]))

4.777777777777778


In [9]:
b= np.ones([5,5], dtype = int)
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
i=0
# x = np.mean(b[i:i+3, i:i+3]))
# print(x)
print(b[b+1])

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
